[workspace]
default-members = ["crystal_snapshots"]
members = [ "crystal_snapshots"]
resolver = "2"

[workspace.dependencies]
sea-orm = { version = "0.12.14", features = [
    "runtime-tokio-rustls",
    "sqlx-mysql",
] }
